### ISSUE TITLE
Exibir "loading.." nos updates

### ISSUE THREAD

**Issue by fabiozaffani** [onyxcorp/pagapoco#14]
Toda vez que o site precisa sincronizar com o servidor ele passa por uma sequência de 3 eventos que sempre são enviados pelo Dispatcher, a sequência é:

FOO_UPDATE_START
FOO_UPDATE_ERROR
FOO_UPDATE_SUCCESS

O evento START sempre é enviado no começo de qualquer requisição a Api's externas para manter o aplicativo realtime e sync, posteriormente na chegada dos resultados o ERROR / SUCCESS são disparados.

É necessário que o sistema sempre informe algo neste período entre o START e o ERROR / SUCCESS, algo como fazer o React exibir uma bolinha de loading ou algum aviso "Carregando..."

**Comment by husek** [comment]
View: 
https://github.com/onyxcorp/pagapoco/pull/32

**Comment by fabiozaffani** [comment]
Done!
