### ISSUE TITLE
Gráfico de histórico de preços

### ISSUE THREAD

**Issue by fabiozaffani** [onyxcorp/pagapoco#19]
Algumas datas de preço podem vir desfalcados de um ou outro dia, mas o gráfico de preço precisa sempre mostrar algum valor para o dia atual e também não deixar gaps entre os dias anteriores (ele precisa ter um valor diário).

Uma solução seria fazer com que o sistema preencha automaticamente os valores faltantes preenchendo os valores possivelmente defasados com o valor do dia anterior.

**Comment by yneves** [comment]
Só pra confirmar, tá faltando mesmo a store do ProductPriceHistory certo? Segue o mesmo padrão da ProductStore?

**Comment by fabiozaffani** [comment]
Isso, no caso a Store serve como um agregador de conteúdo, ou seja, o ProductPriceHistory pode ser chamado dentro da ProductStore, apesar dele ser separado na parte de ActionCreator e Api na Store eles ficam juntos. Enfim pode usar a ProductStore mesmo e ampliar ela.

**Comment by yneves** [comment]
Eu acabei criando uma store só para o histórico de preços enquanto penso uma forma de integrar melhor à store dos produtos. Assim posso trabalhar no gráfico e mudar a store depois.

**Comment by fabiozaffani** [comment]
Tudo bem! Depois se precisar eu te ajudo com o código e a integração.
