### ISSUE TITLE
Busca na página interna

### ISSUE THREAD

**Issue by fabiozaffani** [onyxcorp/pagapoco#25]
Não é possível ativar a busca quando realizada da página interna do produto, como ela esta detectando apenas quando se digita com o teclado (sem nenhum tipo de ativação como enter) a página não atualiza.

**Comment by yneves** [comment]
Neste caso deve manter a url do produto? Acho que a solução aqui é limpar o _current assim o products.jsx renderiza a lista filtrada já. Aí a questão da url pode manter a do produto ou mudar pra raiz.

**Comment by fabiozaffani** [comment]
Enquanto que na página principal a busca vai sendo executada conforme o usuário digita, eu acho que na página interna de produto é bom fazer com que ele tenha que apertar enter ou clicar em algum botão de busca, então seria outro tipo de evento.

Talvez o componente de busca tenha que ter alguma variável para detectar a página atual, assim ele sabe que o evento de "change" é executado somente em determinadas páginas enquanto que em outras ele só executa quando o usuário pressionar enter ou clicar em um botão na busca.

**Comment by yneves** [comment]
Fiz a alteração. Se estiver na home filtra enquanto digitar. Nas outras páginas apenas ao clicar no botão, neste caso vai para a home ver os resultados.
