### ISSUE TITLE
home - Criar um layout para uma home page (exemplos)

### ISSUE THREAD

**Issue by fabiozaffani** [onyxcorp/pagapoco#58]
A home page deve incentivar bastante o campo de busca (nossa principal ferramenta) e logo abaixo mostrar alguns produtos (exibir a lista com os maiores/melhores descontos). Abaixo seguem os 3 principais exemplos desta idéia.

![exemplos-home-pages](https://cloud.githubusercontent.com/assets/1018480/5810480/5de4d042-a02e-11e4-8345-bb8bb7679ff0.jpg)

**Comment by husek** [comment]
View: https://github.com/onyxcorp/pagapoco/pull/81

**Comment by fabiozaffani** [comment]
Done
