### ISSUE TITLE
Loop em products.jsx

### ISSUE THREAD

**Issue by fabiozaffani** [onyxcorp/pagapoco#8]
O loop iniciado na linha 52 precisa ser refatorado de forma que ele utilize o forEach nativo da collection products (this.state.products), no momento está utilizando um for loop padrão.

**Comment by yneves** [comment]
Só pra constar, eu troquei o forEach pelo loop simples em função de performance. Um loop normal é sempre mais rápido que forEach ou map, mesmo que a diferença não seja perceptível numa lista pequena. Vou retornar com o map como estava.

**Comment by fabiozaffani** [comment]
Concordo na questão da performance, eu mesmo normalmente sou maníaco por otimização, mas é que é bem como você falou, a lista por ser pequena (mesmo em produção será não muito grande) acho que acaba sendo melhor deixar com o forEach pela legibilidade, já que fica bem claro que se trata de um objeto do tipo collection.

Enfim, normalmente eu sempre tenho prezado pela legibilidade mesmo que um pouco em detrimento da performance, e otimizar somente quando percebermos um gargalo no código.

O que acha?

**Comment by yneves** [comment]
Sem problemas. Se precisar otimizamos depois. Já fiz a alteração.
