### ISSUE TITLE
Validação no app.jsx

### ISSUE THREAD

**Issue by fabiozaffani** [onyxcorp/pagapoco#80]
Necessário adicionar uma validação se o link.type existe no componente app.jsx, mais especificamente em:
if (this.state.route.status == 'success') {
                 switch(this.state.route.link.type) {

Rotas não encontradas pelo router farão com que ele acuse um erro onde link não esta defined.

**Comment by husek** [comment]
View: https://github.com/onyxcorp/pagapoco/pull/81

**Comment by fabiozaffani** [comment]
Done
